### ISSUE TITLE
text field misplacement

### ISSUE THREAD

**Issue by willbrea** [EarnForex/PriceAlert#1]
Hello, 

I recently downloaded price alert and it all seems to work fine except one minor detail that bugs me. The text field is placed outside the designated window. See attached image file. Hopefully this is an easy fix.

Thank you
[price alert screenshot.docx](https://github.com/EarnForex/PriceAlert/files/6028717/price.alert.screenshot.docx)

**Comment by EarnForex** [comment]
Thanks for reporting!
