### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by jmmac1973** [EarnForex/PriceAlert#3]
Hi,

This indicator seems to do all I'm looking for:
- Use of mouse to easily place alerts;
- Simple and practical;
- Push and local alerts.

But I think it could be improved in the following:
Allow disabling the alert by clicking in the alert type label like (ex: "Above Price"). The only way I find to disable it is putting "0" in the value.

Just testing right now I found what seems to be a bug: If I set an alert and then I delete the alert line in the chart, the indicator malfunctions and no longer lets me set an alert. If I click the alert type label, it shows a price for a second and then changes to "0" again.

Kind regards.

**Comment by EarnForex** [comment]
Thanks for reporting! I will look into it.

**Comment by jmmac1973** [comment]
Another possible improvement would be an setting to activate the alerts always using the BID price. Since in MT charts use the bid and you usually place the alerts visually using a line, If the broker is not ECN, spreads will be bigger and sometimes the alert will trigger early.
With an option to change this behaviour, everyone will be happy!

**Comment by EarnForex** [comment]
Fixed in 1.04.
